// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4jQ9wy-cBbcnTPlq5qj6ARTf2LoXSu3Q',
    appId: '1:682828945612:web:71fdc4f35f5acfe4d94a69',
    messagingSenderId: '682828945612',
    projectId: 'exercise-type-test-68fc7',
    authDomain: 'exercise-type-test-68fc7.firebaseapp.com',
    storageBucket: 'exercise-type-test-68fc7.appspot.com',
    measurementId: 'G-RXHCNQ7SQZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU5n1aEPCnAQwI42e-4DdFRKgYNR5FMms',
    appId: '1:682828945612:android:c29d11c5235c9fd8d94a69',
    messagingSenderId: '682828945612',
    projectId: 'exercise-type-test-68fc7',
    storageBucket: 'exercise-type-test-68fc7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpzfREpJ7a2ceYUiiTiUK9SjN16fN46zA',
    appId: '1:682828945612:ios:9f57800c6c2eaec5d94a69',
    messagingSenderId: '682828945612',
    projectId: 'exercise-type-test-68fc7',
    storageBucket: 'exercise-type-test-68fc7.appspot.com',
    iosClientId: '682828945612-gf5ma13hfv4plo7g98b92vop70h2rm1k.apps.googleusercontent.com',
    iosBundleId: 'com.example.exerciseTypeTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpzfREpJ7a2ceYUiiTiUK9SjN16fN46zA',
    appId: '1:682828945612:ios:9f57800c6c2eaec5d94a69',
    messagingSenderId: '682828945612',
    projectId: 'exercise-type-test-68fc7',
    storageBucket: 'exercise-type-test-68fc7.appspot.com',
    iosClientId: '682828945612-gf5ma13hfv4plo7g98b92vop70h2rm1k.apps.googleusercontent.com',
    iosBundleId: 'com.example.exerciseTypeTest',
  );
}
